/**
 * Where the database lives.
 *
 * Overridable via FBGP_DB so tests, experiments and throwaway runs can point at
 * a scratch file instead of the real one. The real database holds hand-curated
 * work — group activation, composer types, per-group rules — that cannot be
 * regenerated by re-running the importer, so nothing should ever write to it
 * casually.
 */
export const DB_PATH = process.env.FBGP_DB ?? 'data/app.db';
